kind: ConfigMap
apiVersion: v1
metadata:
  name: backend
data:
  ENV_HOST=mysql

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend
  labels:
    project: expense
    environment: dev
    module: backend
    tier: api
spec:
  replicas: 2
  matchLabels: 
    project: expense
    environment: dev
    module: backend
    tier: api
  template:
    metadata:
      labels:
        project: expense
        environment: dev
        module: backend
        tier: api
    spec:
      containers:
      - name: backend
        image: sirishasai2105/backend:v1

---
kind: Service
apiVersion: v1
metadata:
  name: backend-svc
spec:
  selector:
    project: expense
    environment: dev
    module: backend
    tier: api
  ports:
    name: backend-svc
    protocol: TCP
    port: 8080
    targetPort: 8080



  
